name: Deploy Lambda Functions
on:
  push:
   
    branches-ignore: main

jobs:
  release:
    name: Deploy lambda function
    runs-on: [ ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id:  ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

        aws-region: us-east-1
    - name: zip Lambda Function
      run: |
        zip -r9 lambda.zip . send.py
    - name: AWS Deploy
      run: |
        aws lambda update-function-code --function-name deploy-sample --zip-file fileb://lambda.zip
